In [16]:
import pandas as pd

In [17]:
test_data = pd.read_json("test_data_LIMPIO.json")

In [18]:
test_data.sample(15)

,label,text,Dataset
5661,2,montreal black white street studio lecture hal...,Amazon Review Polarity Dataset
25378,2,got told fun work score,Sentiment140
13422,0,horrible never argues stylist much life came e...,Yelp Polarity Reviews
50647,0,liability,Stanford
53469,1,devastating horror suffered entire people,Stanford
30190,0,hanging prolly gon na go lay lil bit got headache,Sentiment140
45666,2,dramatic interest,Stanford
27567,0,rainy day,Sentiment140
14903,2,friend stopped zuzu cafe brood small child tri...,Yelp Polarity Reviews
27321,0,put good show politics show missed known would...,Sentiment140
32362,0,sad,Sentiment140
13677,0,one star given negative star rating option wai...,Yelp Polarity Reviews
12033,2,started using toner two day later multiple peo...,Amazon Review Polarity Dataset
30354,0,strained left knee,Sentiment140
9634,0,disaster portraying anyone volunteer admirable...,Amazon Review Polarity Dataset

In [19]:
grouped = test_data.groupby('Dataset')

# Paso 3: Crear un diccionario de DataFrames
tests = {name: group for name, group in grouped}

In [20]:
amazon_test = tests["Amazon Review Polarity Dataset"]
yelp_test = tests["Yelp Polarity Reviews"]
financial_test = tests["Financial Phrasebank"]
stanford_test = tests["Stanford"]
sentiment_test = tests["Sentiment140"]
imdb_test = tests["Movie Database (IMDb)"]
tweets_test = tests["Twitter US Airline Sentiment"]

In [26]:
amazon_test.to_json("AMAZON_TEST_LIMPIO.json")
yelp_test.to_json("YELP_TEST_LIMPIO.json")
financial_test.to_json("FINANCIAL_TEST_LIMPIO.json")
stanford_test.to_json("STANFORD_TEST_LIMPIO.json")
sentiment_test.to_json("SENTIMENT140_TEST_LIMPIO.json")
imdb_test.to_json("IMDB_TEST_LIMPIO.json")
tweets_test.to_json("TWEETS_TEST_LIMPIO.json")